export const products = [
  {
    id: 1,
    name: "Golden Ring — Classic",
    price: 249,
    description: "Elegant 14K gold ring with a smooth polished surface.",
    gender: "women",
    rating: 4.7,
    type: "ring",
    material: "gold",
    specifications: ["14K gold", "Polished surface", "Classic design"],
    images: [
      "https://moonmagic.com/cdn/shop/files/PIC-GOLD-WR-MBAND-1A_1_856x.jpg?v=1750183584",
      "https://moonmagic.com/cdn/shop/files/PIC-GOLD-WR-MBAND-1A_3_da42ae87-4d4f-4210-8211-10a08bb21b70_856x.jpg?v=1750183584",
      "https://moonmagic.com/cdn/shop/files/PIC-GOLD-WR-MBAND-1A_2_856x.jpg?v=1750183584",
    ],
    reviews: 120,
    brand: "Aurora Jewels",
  },
  {
    id: 2,
    name: "Diamond Ring — Aurora",
    price: 1299,
    description: "Premium ring with a 0.5ct natural diamond and gold frame.",
    gender: "women",
    rating: 4.9,
    type: "ring",
    material: "silver",
    specifications: ["0.5ct diamond", "Gold frame", "Premium craftsmanship"],
    images: [
      "https://www.peoplesjewellers.com/productimages/processed/V-19209220_0_800.jpg?pristine=true",
      "https://www.peoplesjewellers.com/productimages/processed/V-19209220_2_800.jpg?pristine=true",
      "https://www.peoplesjewellers.com/productimages/processed/V-19209220_1_800.jpg?pristine=true",
    ],
    reviews: 250,
    brand: "Celeste Diamonds",
  },
  {
    id: 3,
    name: "Silver Necklace — Infinity",
    price: 149,
    description: "Sterling silver necklace with infinity symbol pendant.",
    gender: "women",
    rating: 4.5,
    type: "necklace",
    material: "silver",
    specifications: ["Sterling silver", "Infinity pendant", "Adjustable chain"],
    images: [
      "https://www.michaelhill.ca/dw/image/v2/AANC_PRD/on/demandware.static/-/Sites-MHJ_Master/default/dw712b4664/images/P18149838/P18149838-15-22.jpg?sw=1000&sm=fit&q=90",
      "https://www.michaelhill.ca/dw/image/v2/AANC_PRD/on/demandware.static/-/Sites-MHJ_Master/default/dw9a8264a7/images/P18149838/P18149838-15-21.jpg?sw=1000&sm=fit&q=90",
      "https://www.michaelhill.ca/dw/image/v2/AANC_PRD/on/demandware.static/-/Sites-MHJ_Master/default/dw5dfd8459/images/P18149838/P18149838-15-27.jpg?sw=1000&sm=fit&q=90",
    ],
    reviews: 95,
    brand: "Infinity Luxe",
  },
  {
    id: 4,
    name: "Gold Necklace — Sunlight",
    price: 499,
    description: "18K gold necklace with minimalist sun pendant.",
    gender: "women",
    rating: 4.8,
    type: "necklace",
    material: "gold",
    specifications: ["18K gold", "Sun pendant", "Minimalist design"],
    images: [
      "https://cdn.shopify.com/s/files/1/0589/0723/0373/files/MondayMonarch-61-sun_1_cut_600x.jpg",
      "https://www.mondaymonarch.com/cdn/shop/products/FreeStylenecklacespicsfor-sunonlywhite_bc4424a4-6b7b-49fe-ae4a-7f91127dc904_600x.jpg?v=1717407319",
      "https://www.mondaymonarch.com/cdn/shop/products/reviewedSunnecklaceforshopify_5_600x.jpg?v=1686476637",
    ],
    reviews: 180,
    brand: "SunAura Gold",
  },
  {
    id: 5,
    name: "Pearl Earrings — Luna",
    price: 199,
    description: "Freshwater pearl earrings with silver hooks.",
    gender: "women",
    rating: 4.6,
    type: "earrings",
    material: "silver",
    specifications: ["Freshwater pearls", "Silver hooks", "Elegant style"],
    images: [
      "https://cdn.shopify.com/s/files/1/0589/0723/0373/files/IMG_2201_-_pearl_dangle_cut_-_after_extra_edit_600x.jpg",
      "https://www.mondaymonarch.com/cdn/shop/files/SHP_1818_cut2_600x.jpg?v=1696187484",
      "https://www.mondaymonarch.com/cdn/shop/files/SHP_1837_cut_600x.jpg?v=1696187484",
    ],
    reviews: 75,
    brand: "Luna Pearls",
  },
  {
    id: 6,
    name: "Diamond Earrings — Nova",
    price: 899,
    description: "Earrings with micro-pavé diamond stones, 18K gold.",
    gender: "women",
    rating: 4.9,
    type: "earrings",
    material: "silver",
    specifications: ["Micro-pavé diamonds", "18K gold", "Luxury finish"],
    images: [
      "https://www.michaelhill.ca/dw/image/v2/AANC_PRD/on/demandware.static/-/Sites-MHJ_Master/default/dw705f6574/images/P21438783/P21438783-517-21.jpg?sw=1000&sm=fit&q=90",
      "https://www.michaelhill.ca/dw/image/v2/AANC_PRD/on/demandware.static/-/Sites-MHJ_Master/default/dw668231cc/images/P21438783/P21438783-517-22.jpg?sw=1000&sm=fit&q=90",
      "https://www.michaelhill.ca/dw/image/v2/AANC_PRD/on/demandware.static/-/Sites-MHJ_Master/default/dw82c53963/images/P21438783/P21438783-517-27.jpg?sw=1000&sm=fit&q=90",
    ],
    reviews: 210,
    brand: "Nova Gems",
  },
  {
    id: 7,
    name: "Silver Bracelet — Harmony",
    price: 129,
    description: "925 silver bracelet with minimalistic geometric charms.",
    gender: "unisex",
    rating: 4.4,
    type: "bracelet",
    material: "silver",
    specifications: ["925 silver", "Geometric charms", "Minimalist design"],
    images: [
      "https://asset.swarovski.com/images/$size_1450/t_swa103/b_rgb:ffffff,c_scale,dpr_2.0,f_auto,w_675/5524421_png_var3/hyperbola-bracelet--infinity-and-heart--white--rhodium-plated-swarovski-5524421.png",
      "https://asset.swarovski.com/images/$size_1450/t_swa103/b_rgb:ffffff,c_scale,dpr_2.0,f_auto,w_675/5524421_png/hyperbola-bracelet--infinity-and-heart--white--rhodium-plated-swarovski-5524421.png",
      "https://asset.swarovski.com/images/$size_1450/t_swa002/c_scale,dpr_2.0,f_auto,w_675/5524421_ms1/hyperbola-bracelet--infinity-and-heart--white--rhodium-plated-swarovski-5524421.jpg",
    ],
    reviews: 60,
    brand: "Harmony Silver",
  },
  {
    id: 8,
    name: "Gold Bracelet — Imperial",
    price: 359,
    description: "Luxurious 14K gold chain bracelet with secure clasp.",
    gender: "women",
    rating: 4.7,
    type: "bracelet",
    material: "gold",
    specifications: ["14K gold", "Chain design", "Secure clasp"],
    images: [
      "https://asset.swarovski.com/images/$size_1450/t_swa103/b_rgb:ffffff,c_scale,dpr_2.0,f_auto,w_675/5646745_png_var3/one-bracelet--heart--pink--rose-gold-tone-plated-swarovski-5646745.png",
      "https://asset.swarovski.com/images/$size_1450/t_swa103/b_rgb:ffffff,c_scale,dpr_2.0,f_auto,w_675/5646745_png/one-bracelet--heart--pink--rose-gold-tone-plated-swarovski-5646745.png",
      "https://asset.swarovski.com/images/$size_1450/t_swa002/c_scale,dpr_2.0,f_auto,w_675/5646745_ms1/one-bracelet--heart--pink--rose-gold-tone-plated-swarovski-5646745.jpg",
    ],
    reviews: 130,
    brand: "Imperial Gold",
  },
  {
    id: 9,
    name: "Men’s Chain — Titan Steel",
    price: 179,
    description: "Durable stainless steel chain with a matte finish.",
    gender: "men",
    rating: 4.3,
    type: "necklace",
    material: "silver",
    specifications: ["Stainless steel", "Matte finish", "Durable design"],
    images: [
      "https://michaelkors.scene7.com/is/image/MichaelKors/MKJ0251-0991_1?$large$",
      "https://www.peoplesjewellers.com/productimages/processed/V-20521787_1_800.jpg?pristine=true",
      "https://www.peoplesjewellers.com/productimages/processed/V-20521787_2_800.jpg?pristine=true",
    ],
    reviews: 85,
    brand: "Titan Steelworks",
  },
  {
    id: 10,
    name: "Men’s Gold Chain — Royal",
    price: 739,
    description: "Heavy gold-plated chain for a bold premium look.",
    gender: "men",
    rating: 4.8,
    type: "necklace",
    material: "gold",
    specifications: ["Gold-plated", "Heavy chain", "Premium look"],
    images: [
      "https://www.peoplesjewellers.com/productimages/processed/V-20577056_0_800.jpg?pristine=true",
      "https://www.peoplesjewellers.com/productimages/processed/V-20577056_2_800.jpg?pristine=true",
    ],
    reviews: 160,
    brand: "Royal Chains",
  },
  {
    id: 11,
    name: "Silver Ring — Vintage",
    price: 89,
    description: "Antique-style silver ring with engraved details.",
    gender: "unisex",
    rating: 4.2,
    type: "ring",
    material: "silver",
    specifications: ["Antique style", "Engraved details", "Silver material"],
    images: [
      "https://www.peoplesjewellers.com/productimages/processed/V-20582956_0_800.jpg?pristine=true",
      "https://www.peoplesjewellers.com/productimages/processed/V-20582956_2_800.jpg?pristine=true",
      "https://www.peoplesjewellers.com/productimages/processed/V-20582956_1_800.jpg?pristine=true",
    ],
    reviews: 55,
    brand: "Vintage Silver",
  },
  {
    id: 12,
    name: "Engagement Ring — Eternal Love",
    price: 1599,
    description: "High-end engagement ring with a brilliant-cut diamond.",
    gender: "women",
    rating: 5.0,
    type: "ring",
    material: "gold",
    specifications: ["Brilliant-cut diamond", "Gold band", "Engagement design"],
    images: [
      "https://assets.vrai.com/25216/1748933345-33-df619w060-l-33-d37659a-front-yellow.jpg?auto=compress&fit=crop&crop=focalpoint&crop=focalpoint&fm=avif&q=75&w=600&h=600&dpr=2",
      "https://assets.vrai.com/25216/1748933345-33-df619w060-l-33-d37659a-upright-1-yellow.jpg?auto=compress&fit=crop&crop=focalpoint&crop=focalpoint&fm=avif&q=75&w=600&h=600&dpr=2",
      "https://assets.vrai.com/25216/1749152941-v-eternity-wb-04ct_yg_on-model-1.jpg?auto=compress&fit=crop&crop=focalpoint&crop=focalpoint&fm=avif&q=75&w=600&h=600&dpr=2",
    ],
    reviews: 300,
    brand: "Eternal Love",
  },
  {
    id: 13,
    name: "Gold Earrings — Leaf",
    price: 279,
    description: "14K gold earrings shaped like delicate leaves.",
    gender: "women",
    rating: 4.6,
    type: "earrings",
    material: "gold",
    specifications: ["14K gold", "Leaf design", "Delicate style"],
    images: [
      "https://ecksand.com/cdn/shop/products/Ecksand-09582-y-face_2048x.png?v=1684162662",
      "https://ecksand.com/cdn/shop/products/ecksand_9582.bo.d-y-18_earrings_marilou_b_1080x.jpg?v=1684162662",
      "https://ecksand.com/cdn/shop/products/ecksand_24769.d-y-14_09582.bo.d-r-18_jewelry_annaise_a_1080x.jpg?v=1684162662",
    ],
    reviews: 110,
    brand: "Leaf Luxe",
  },
  {
    id: 14,
    name: "Sapphire Necklace — Royal Blue",
    price: 1299,
    description: "Luxury necklace with natural sapphire gemstone.",
    gender: "women",
    rating: 4.9,
    type: "necklace",
    material: "silver",
    specifications: ["Natural sapphire", "Luxury design", "Silver chain"],
    images: [
      "https://www.peoplesjewellers.com/productimages/processed/V-20042787_0_800.jpg?pristine=true",
      "https://www.peoplesjewellers.com/productimages/processed/V-20042787_1_800.jpg",
      "https://www.peoplesjewellers.com/productimages/processed/V-20042787_2_800.jpg?pristine=true",
    ],
    reviews: 220,
    brand: "Royal Blue Gems",
  },
  {
    id: 15,
    name: "Ruby Ring — Scarlet Flame",
    price: 899,
    description: "Stunning ring with a natural ruby centerpiece.",
    gender: "women",
    rating: 4.8,
    type: "ring",
    material: "gold",
    specifications: ["Natural ruby", "Gold band", "Elegant design"],
    images: [
      "https://www.peoplesjewellers.com/productimages/processed/V-20621985_0_800.jpg?pristine=true",
      "https://www.peoplesjewellers.com/productimages/processed/V-20621985_2_800.jpg?pristine=true",
      "https://cdn.tangiblee.com/yruler-merger/Bags/Textures/14469947/Lifestyle/8748/gallery.jpeg",
    ],
    reviews: 190,
    brand: "Scarlet Flame",
  },
];
